PREFIX: '§f〔幻嵐助手〕§r'

ITEM_LORE:
  - '&f購買前請確認購買物品是正確'
  - ''
  - '&c!注意 買錯無法退貨'

PERMISSIONS:
  USE: "hu_building.shop"
  # 設定 hu_building.VIP1
  VIP:
    DEFAULT: 1
    VIP5: 0.9
    VIP6: 0.8
    VIP7: 0.7
    VIP8: 0.6



BUILDING_MATERIAL_BLOCK:
  GUINAME: '              &1&L建材方塊'
  BLOCK:
    - 'OAK_LOG,木頭類,1'
    - 'OAK_LEAVES,葉子類,2'
    - 'GRASS_BLOCK,泥土類,3'
    - 'STONE,石頭類 磚塊類,4'
    - 'SAND,沙類,5'
    - 'SEA_LANTERN,海洋類,6'
    - 'END_STONE,終界類 地域類,7'
    - 'BEE_NEST,其他,8'
  TYPE_1: #木頭類
    - 'OAK_LOG,橡木原木,24'
    - 'SPRUCE_LOG,杉木原木,24'
    - 'BIRCH_LOG,樺木原木,24'
    - 'JUNGLE_LOG,叢林木原木,24'
    - 'ACACIA_LOG,相思木原木,24'
    - 'DARK_OAK_LOG,黑橡木原木,24'
    - 'MANGROVE_LOG,紅樹林木原木,24'
    - 'CHERRY_LOG,櫻花木原木,24'
    - 'BAMBOO_BLOCK,竹方塊,24'
    - 'STRIPPED_OAK_LOG,剝皮橡木原木,26'
    - 'STRIPPED_SPRUCE_LOG,剝皮杉木原木,26'
    - 'STRIPPED_BIRCH_LOG,剝皮樺木原木,26'
    - 'STRIPPED_JUNGLE_LOG,剝皮叢林木原木,26'
    - 'STRIPPED_ACACIA_LOG,剝皮相思木原木,26'
    - 'STRIPPED_DARK_OAK_LOG,剝皮黑橡木原木,26'
    - 'STRIPPED_MANGROVE_LOG,剝皮紅樹林木原木,26'
    - 'STRIPPED_CHERRY_LOG,剝皮櫻花木原木,26'
    - 'STRIPPED_BAMBOO_BLOCK,剝皮竹方塊,26'
    - 'OAK_PLANKS,橡木材,6'
    - 'SPRUCE_PLANKS,杉木材,6'
    - 'BIRCH_PLANKS,樺木材,6'
    - 'JUNGLE_PLANKS,叢林木材,6'
    - 'ACACIA_PLANKS,相思木材,6'
    - 'DARK_OAK_PLANKS,黑橡木材,6'
    - 'MANGROVE_PLANKS,紅樹林木材,6'
    - 'CHERRY_PLANKS,櫻花木材,6'
    - 'BAMBOO_PLANKS,竹材,6'
    - 'CRIMSON_STEM,緋紅蕈柄,32'
    - 'STRIPPED_CRIMSON_STEM,剝皮緋紅蕈柄,34'
    - 'WARPED_STEM,扭曲蕈柄,32'
    - 'STRIPPED_WARPED_STEM,剝皮扭曲蕈柄,34'
  TYPE_2: #葉子類
    - 'OAK_LEAVES,橡木樹葉,5'
    - 'SPRUCE_LEAVES,杉木樹葉,5'
    - 'BIRCH_LEAVES,樺木樹葉,5'
    - 'JUNGLE_LEAVES,叢林木樹葉,5'
    - 'ACACIA_LEAVES,相思木樹葉,5'
    - 'DARK_OAK_LEAVES,黑橡木樹葉,5'
    - 'MANGROVE_LEAVES,紅樹林木樹葉,5'
    - 'CHERRY_LEAVES,櫻花木樹葉,5'
    - 'NULL'
    - 'AZALEA_LEAVES,杜鵑葉,7'
    - 'FLOWERING_AZALEA_LEAVES,開花的杜鵑葉,7'
  TYPE_3: #泥土類
    - 'GRASS_BLOCK,草地,6'
    - 'DIRT,泥土,6'
    - 'COARSE_DIRT,粗泥,20'
    - 'PODZOL,灰壤,20'
    - 'MYCELIUM,菌絲土,20'
    - 'CRIMSON_NYLIUM,緋紅菌絲石,30'
    - 'WARPED_NYLIUM,扭曲菌絲土,30'
    - 'MUD_BRICKS,泥磚,36'
  TYPE_4: #石頭類 磚塊類
    - 'STONE,石頭,6'
    - 'COBBLESTONE,鵝卵石,4'
    - 'SMOOTH_STONE,平滑石頭,20'
    - 'MOSSY_COBBLESTONE,青苔鵝卵石,8'
    - 'MOSS_BLOCK,苔癬方塊,12'
    - 'MOSSY_STONE_BRICKS,青苔石磚,25'
    - 'CHISELED_STONE_BRICKS,浮雕石磚,25'
    - 'STONE_BRICKS,石磚,25'
    - 'GRAVEL,礫石,12'
    - 'CRACKED_STONE_BRICKS,裂紋石磚,25'
    - 'SMOOTH_BASALT,平滑玄武岩,22'
    - 'BLACKSTONE,黑石,22'
    - 'DEEPSLATE,深板岩,22'
    - 'COBBLED_DEEPSLATE,身板岩碎石,22'
    - 'NULL'
    - 'NULL'
    - 'NULL'
    - 'NULL'
    - 'GRANITE,花崗岩,10'
    - 'POLISHED_GRANITE,拋光花崗岩,16'
    - 'DIORITE,閃長岩,10'
    - 'POLISHED_DIORITE,拋光閃長岩,16'
    - 'ANDESITE,安山岩,10'
    - 'POLISHED_ANDESITE,拋光安山岩,16'
    - 'NULL'
    - 'NULL'
    - 'NULL'
    - 'BRICKS,紅磚,12'
    - 'CALCITE,方解石,18'
    - 'DRIPSTONE_BLOCK,鐘乳石方塊,18'


  TYPE_5: #沙類
    - 'SAND,沙,4'
    - 'SANDSTONE,砂岩,12'
    - 'CHISELED_SANDSTONE,浮雕砂岩,12'
    - 'CUT_SANDSTONE,切製沙岩,12'
    - 'SMOOTH_SANDSTONE,平滑砂岩,40'
    - 'NULL'
    - 'NULL'
    - 'NULL'
    - 'NULL'
    - 'RED_SAND,紅沙,4'
    - 'RED_SANDSTONE,紅砂岩,12'
    - 'CHISELED_RED_SANDSTONE,浮雕紅砂岩,12'
    - 'CUT_RED_SANDSTONE,切製紅沙岩,12'
    - 'SMOOTH_RED_SANDSTONE,平滑紅砂岩,40'
  TYPE_6: #海洋類
    - 'ICE,冰,4'
    - 'SNOW_BLOCK,雪塊,4'
    - 'PACKED_ICE,冰磚,12'
    - 'BLUE_ICE,藍冰,20'
    - 'NULL'
    - 'SEA_LANTERN,海燈籠,48'
    - 'PRISMARINE,海磷石,20'
    - 'PRISMARINE_BRICKS,海磷石磚,20'
    - 'DARK_PRISMARINE,暗海磷石,32'
    - 'TUBE_CORAL_BLOCK,管珊瑚方塊,16'
    - 'BUBBLE_CORAL_BLOCK,氣泡珊瑚方塊,16'
    - 'HORN_CORAL_BLOCK,角珊瑚方塊,16'
    - 'FIRE_CORAL_BLOCK,火珊瑚方塊,16'
    - 'BRAIN_CORAL_BLOCK,腦珊瑚方塊,16'
    - 'NULL'
    - 'NULL'
    - 'NULL'
    - 'NULL'
    - 'DEAD_TUBE_CORAL_BLOCK,死亡的管珊瑚方塊,16'
    - 'DEAD_BUBBLE_CORAL_BLOCK,死亡的氣泡珊瑚方塊,16'
    - 'DEAD_HORN_CORAL_BLOCK,死亡的角珊瑚方塊,16'
    - 'DEAD_FIRE_CORAL_BLOCK,死亡的火珊瑚方塊,16'
    - 'DEAD_BRAIN_CORAL_BLOCK,死亡的腦珊瑚方塊,16'
  TYPE_7: #終界類 地域類
    - 'NETHERRACK,地獄石,4'
    - 'RED_NETHER_BRICKS,紅地獄磚,12'
    - 'NETHER_BRICKS,地獄磚,12'
    - 'SOUL_SAND,靈魂砂,4'
    - 'SOUL_SOIL,靈魂土,16'
    - 'OBSIDIAN,黑曜石,40'
    - 'POLISHED_BLACKSTONE_BRICKS,拋光黑石磚,32'
    - 'CRYING_OBSIDIAN,哭泣的黑曜石,50'
    - 'NULL'
    - 'QUARTZ_BLOCK,石英方塊,12'
    - 'CHISELED_QUARTZ_BLOCK,浮雕石英磚,20'
    - 'QUARTZ_PILLAR,石英柱,25'
    - 'SMOOTH_QUARTZ,平滑石英方塊,20'
    - 'QUARTZ_BRICKS,石英磚,50'
    - 'NULL'
    - 'NULL'
    - 'NULL'
    - 'NULL'
    - 'MAGMA_BLOCK,岩漿塊,4'
    - 'GLOWSTONE,螢光石,12'
    - 'SHROOMLIGHT,譚光體,16'
    - 'NULL'
    - 'NULL'
    - 'NULL'
    - 'NULL'
    - 'NULL'
    - 'NULL'
    - 'END_STONE,終界石,4'
    - 'END_STONE_BRICKS,終界石磚,8'
    - 'PURPUR_BLOCK,紫珀方塊,10'
    - 'PURPUR_PILLAR,紫珀柱,20'


  TYPE_8: #其他
    - 'BEE_NEST,蜂窩,18'
    - 'HONEYCOMB_BLOCK,蜂巢塊,32'
    - 'HONEY_BLOCK,蜂蜜塊,32'
    - 'OCHRE_FROGLIGHT,赭黃蛙光體,36'
    - 'PEARLESCENT_FROGLIGHT,珠紫蛙光體,36'
    - 'VERDANT_FROGLIGHT,蒼翠蛙光體,36'
    - 'NULL'
    - 'NULL'
    - 'NULL'
    - 'BOOKSHELF,書櫃,24'
    - 'COBWEB,蜘蛛網,12'



DYED_BLOCK:
  GUINAME: '              &1&L染色方塊'
  BLOCK:
    - 'WHITE_WOOL,羊毛類,1'
    - 'TERRACOTTA,陶土類,2'
    - 'WHITE_CONCRETE,混凝土類,3'
    - 'WHITE_GLAZED_TERRACOTTA,釉陶類,4'
    - 'GLASS,玻璃類,5'
  TYPE_1: #羊毛類
    - 'WHITE_WOOL,白色羊毛,14'
    - 'ORANGE_WOOL,橙色羊毛,14'
    - 'MAGENTA_WOOL,洋紅色羊毛,14'
    - 'LIGHT_BLUE_WOOL,淺藍色羊毛,14'
    - 'YELLOW_WOOL,黃色羊毛,14'
    - 'LIME_WOOL,淺綠色羊毛,14'
    - 'PINK_WOOL,粉紅色羊毛,14'
    - 'GRAY_WOOL,灰色羊毛,14'
    - 'LIGHT_GRAY_WOOL,淺灰色羊毛,14'
    - 'CYAN_WOOL,清色羊毛,14'
    - 'PURPLE_WOOL,紫色羊毛,14'
    - 'BLUE_WOOL,藍色羊毛,14'
    - 'BROWN_WOOL,棕色羊毛,14'
    - 'GREEN_WOOL,綠色羊毛,14'
    - 'RED_WOOL,紅色羊毛,14'
    - 'BLACK_WOOL,黑色羊毛,14'
  TYPE_2: #陶土類
    - 'WHITE_TERRACOTTA,白色陶土,15'
    - 'ORANGE_TERRACOTTA,橙色陶土,15'
    - 'MAGENTA_TERRACOTTA,洋紅色陶土,15'
    - 'LIGHT_BLUE_TERRACOTTA,淺藍色陶土,15'
    - 'YELLOW_TERRACOTTA,黃色陶土,15'
    - 'LIME_TERRACOTTA,淺綠色陶土,15'
    - 'PINK_TERRACOTTA,粉紅色陶土,15'
    - 'GRAY_TERRACOTTA,灰色陶土,15'
    - 'LIGHT_GRAY_TERRACOTTA,淺灰色陶土,15'
    - 'CYAN_TERRACOTTA,清色陶土,15'
    - 'PURPLE_TERRACOTTA,紫色陶土,15'
    - 'BLUE_TERRACOTTA,藍色陶土,15'
    - 'BROWN_TERRACOTTA,棕色陶土,15'
    - 'GREEN_TERRACOTTA,綠色陶土,15'
    - 'RED_TERRACOTTA,紅色陶土,15'
    - 'BLACK_TERRACOTTA,黑色陶土,15'
    - 'TERRACOTTA,陶土末,14'
    - 'NULL'
    - 'CLAY,黏土,5'
  TYPE_3: #混凝土類
    - 'WHITE_CONCRETE_POWDER,白色混凝土粉末,12'
    - 'ORANGE_CONCRETE_POWDER,橙色混凝土粉末,12'
    - 'MAGENTA_CONCRETE_POWDER,洋紅色混凝土粉末,12'
    - 'LIGHT_BLUE_CONCRETE_POWDER,淺藍色混凝土粉末,12'
    - 'YELLOW_CONCRETE_POWDER,黃色混凝土粉末,12'
    - 'LIME_CONCRETE_POWDER,淺綠色混凝土粉末,12'
    - 'PINK_CONCRETE_POWDER,粉紅色混凝土粉末,12'
    - 'GRAY_CONCRETE_POWDER,灰色混凝土粉末,12'
    - 'LIGHT_GRAY_CONCRETE_POWDER,淺灰色混凝土粉末,12'
    - 'CYAN_CONCRETE_POWDER,清色混凝土粉末,12'
    - 'PURPLE_CONCRETE_POWDER,紫色混凝土粉末,12'
    - 'BLUE_CONCRETE_POWDER,藍色混凝土粉末,12'
    - 'BROWN_CONCRETE_POWDER,棕色混凝土粉末,12'
    - 'GREEN_CONCRETE_POWDER,綠色混凝土粉末,12'
    - 'RED_CONCRETE_POWDER,紅色混凝土粉末,12'
    - 'BLACK_CONCRETE_POWDER,黑色混凝土粉末,12'
    - 'NULL'
    - 'NULL'
    - 'WHITE_CONCRETE,白色混凝土,14'
    - 'ORANGE_CONCRETE,橙色混凝土,14'
    - 'MAGENTA_CONCRETE,洋紅色混凝土,14'
    - 'LIGHT_BLUE_CONCRETE,淺藍色混凝土,14'
    - 'YELLOW_CONCRETE,黃色混凝土,14'
    - 'LIME_CONCRETE,淺綠色混凝土,14'
    - 'PINK_CONCRETE,粉紅色混凝土,14'
    - 'GRAY_CONCRETE,灰色混凝土,14'
    - 'LIGHT_GRAY_CONCRETE,淺灰色混凝土,14'
    - 'CYAN_CONCRETE,清色混凝土,14'
    - 'PURPLE_CONCRETE,紫色混凝土,14'
    - 'BLUE_CONCRETE,藍色混凝土,14'
    - 'BROWN_CONCRETE,棕色混凝土,14'
    - 'GREEN_CONCRETE,綠色混凝土,14'
    - 'RED_CONCRETE,紅色混凝土,14'
    - 'BLACK_CONCRETE,黑色混凝土,14'

  TYPE_4: #釉陶類
    - 'WHITE_GLAZED_TERRACOTTA,白色釉陶,12'
    - 'ORANGE_GLAZED_TERRACOTTA,橙色釉陶,12'
    - 'MAGENTA_GLAZED_TERRACOTTA,洋紅色釉陶,12'
    - 'LIGHT_BLUE_GLAZED_TERRACOTTA,淺藍色釉陶,12'
    - 'YELLOW_GLAZED_TERRACOTTA,黃色釉陶,12'
    - 'LIME_GLAZED_TERRACOTTA,淺綠色釉陶,12'
    - 'PINK_GLAZED_TERRACOTTA,粉紅色釉陶,12'
    - 'GRAY_GLAZED_TERRACOTTA,灰色釉陶,12'
    - 'LIGHT_GRAY_GLAZED_TERRACOTTA,淺灰色釉陶,12'
    - 'CYAN_GLAZED_TERRACOTTA,清色釉陶,12'
    - 'PURPLE_GLAZED_TERRACOTTA,紫色釉陶,12'
    - 'BLUE_GLAZED_TERRACOTTA,藍色釉陶,12'
    - 'BROWN_GLAZED_TERRACOTTA,棕色釉陶,12'
    - 'GREEN_GLAZED_TERRACOTTA,綠色釉陶,12'
    - 'RED_GLAZED_TERRACOTTA,紅色釉陶,12'
    - 'BLACK_GLAZED_TERRACOTTA,黑色釉陶,12'

  TYPE_5: #玻璃類
    - 'WHITE_STAINED_GLASS,白色玻璃,10'
    - 'ORANGE_STAINED_GLASS,橙色玻璃,10'
    - 'MAGENTA_STAINED_GLASS,洋紅色玻璃,10'
    - 'LIGHT_BLUE_STAINED_GLASS,淺藍色玻璃,10'
    - 'YELLOW_STAINED_GLASS,黃色玻璃,10'
    - 'LIME_STAINED_GLASS,淺綠色玻璃,10'
    - 'PINK_STAINED_GLASS,粉紅色玻璃,10'
    - 'GRAY_STAINED_GLASS,灰色玻璃,10'
    - 'LIGHT_GRAY_STAINED_GLASS,淺灰色玻璃,10'
    - 'CYAN_STAINED_GLASS,清色玻璃,10'
    - 'PURPLE_STAINED_GLASS,紫色玻璃,10'
    - 'BLUE_STAINED_GLASS,藍色玻璃,10'
    - 'BROWN_STAINED_GLASS,棕色玻璃,10'
    - 'GREEN_STAINED_GLASS,綠色玻璃,10'
    - 'RED_STAINED_GLASS,紅色玻璃,10'
    - 'BLACK_STAINED_GLASS,黑色玻璃,10'
    - 'NULL'
    - 'NULL'
    - 'GLASS,玻璃,8'
    - 'TINTED_GLASS,遮光玻璃,12'

OTH_BLOCK:
  GUINAME: '              &1&L其他方塊'
  BLOCK:
    - 'REDSTONE_BLOCK,紅石類,1'
    - 'OAK_SAPLING,樹苗類 花草類,2'
    - 'TUBE_CORAL,珊瑚類(未開放),3'
  TYPE_1: #紅石類
    - 'REDSTONE_BLOCK,紅石方塊,36'
    - 'PISTON,活塞,36'
    - 'STICKY_PISTON,黏性活塞,40'
    - 'DROPPER,投擲器,36'
    - 'DISPENSER,發射器,36'
    - 'JUKEBOX,唱片機,35'
    - 'NOTE_BLOCK,音階盒,35'
    - 'TARGET,標靶,60'
  TYPE_2: #樹苗類
    - 'OAK_SAPLING,橡木樹苗,10'
    - 'SPRUCE_SAPLING,杉木樹苗,10'
    - 'BIRCH_SAPLING,樺木樹苗,10'
    - 'JUNGLE_SAPLING,叢林木樹苗,10'
    - 'DARK_OAK_SAPLING,黑橡木樹苗,10'
    - 'ACACIA_SAPLING,相思木樹苗,10'
    - 'CHERRY_SAPLING,櫻花木樹苗,10'
    - 'NULL'
    - 'NULL'
    - 'DANDELION,蒲公英,10'
    - 'POPPY,罌粟,10'
    - 'AZURE_BLUET,雛草,10'
    - 'OXEYE_DAISY,雛菊,10'
    - 'CORNFLOWER,矢車菊,10'
    - 'SUNFLOWER,向日葵,10'
    - 'LILY_PAD,荷葉,50'
    - 'BIG_DRIPLEAF,大懸葉草,100'
    - 'SPORE_BLOSSOM,袍子花,100'
    - 'VINE,藤蔓,20'
    - 'TWISTING_VINES,扭曲藤,36'
    - 'WEEPING_VINES,垂泣藤,36'




MESSAGE:
  YES_DOWN: '&a購買成功，花費 ⎋%matcoin% 建材點'
  NO_DOWN: '&c購買失敗，您需要 ⎋%matcoin% 建材點'
  INV_NOSLOT: '&c背包沒有空間，無法購買'
  COIN_ERROR: '&c建材點錯誤，請聯絡管理員!'
